[package]
name = "rgbds"
version = "0.1.0"
edition = "2021"
#rust-version = "1.73" # 1.74 will drop support for older Apple platforms we wish to keep supporting.
description = "The premier Game Boy assembly toolchain"
homepage = "https://rgbds.gbdev.io"
repository = "https://github.com/gbdev/rgbds"
license = "MPL-2.0"
keywords = ["rgbds", "gameboy", "asm", "assembly", "gamedev"]
categories = ["command-line-utilities", "development-tools::debugging", "game-development"]

# TODO: move bin-only deps to separate features.
[dependencies] # TODO: audit deps & features
codespan-reporting = "0.11.1"
clap = { version = "3.1.6", features = ["derive"] }
keyword-trie-gen = { path = "keyword-trie-gen" }
lalrpop-util = "0.19.8"
memmap2 = "0.5.8"
parse-display = { version = "0.6.0", default-features = false }
# TODO: maybe use feature `inline-more`
string-interner = { version = "0.14.0", default-features = false, features = ["std","backends"] }
take_mut = "0.2.2"
try-from-discrim = "1.0.0"
warnings-gen = { path = "warnings-gen" }
clap-num = "1.1.1"
thiserror = "1.0.58"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[build-dependencies]
lalrpop = { version = "0.19.8", default-features = false }

[[bin]]
name = "rgbasm"
path = "src/asm/main.rs"

[[bin]]
name = "rgbfix"
path = "src/fix/main.rs"

[workspace]
members = ["keyword-trie-gen", "warnings-gen"]
