[package]
name = "keyword-trie-gen"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.60"
quote = "1.0.25"
syn = { version = "1.0.101", default-features = false, features = ["proc-macro", "parsing", "full"] }
